version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    docker:
      - image: node:12.18.2

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24
        environment:
          TF_LOG: trace
          TF_LOG_PATH: terraform.log

commands:
  setup_aws_credentials:
    steps:
      - run:
          name: create aws credentials and config
          command: |
            mkdir -p ~/.aws
            echo '[default]'                                       > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}"         >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            echo '[default]'           > ~/.aws/config
            echo "region = us-east-1" >> ~/.aws/config

  yarn_install:
    steps:
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules

  create_tfvars:
    parameters:
      stage:
        type: string
    steps:
      - run:
          name: create terraform.tfvars
          command: |
            echo "basic_auth_username = \"${BASIC_AUTH_USERNAME}\""  > ~/project/terraform/envs/<< parameters.stage >>/terraform.tfvars
            echo "basic_auth_password = \"${BASIC_AUTH_PASSWORD}\"" >> ~/project/terraform/envs/<< parameters.stage >>/terraform.tfvars

  terraform:
    parameters:
      stage:
        type: string
      command:
        type: string
    steps:
      - run:
          name: terraform init - << parameters.stage >>
          command: |
            cd ~/project/terraform/envs/<< parameters.stage >>
            terraform init
      - run:
          name: terraform << parameters.command >> - << parameters.stage >>
          command: |
            cd ~/project/terraform/envs/<< parameters.stage >>
            terraform << parameters.command >>
      - store_artifacts:
          path: terraform/envs/<< parameters.stage >>/terraform.log

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn_install
      - run:
          name: eslint
          command: yarn run eslint './src/**/*.ts' './src/**/*.tsx'
      # - run:
      #     name: test
      #     command: yarn run test
      - run:
          name: build
          command: yarn run build
      - slack/status

  tf_plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: install required commands
          command: apk --update add bash curl
      - setup_aws_credentials
      - create_tfvars:
          stage: dev
      - terraform:
          stage: dev
          command: plan
      - create_tfvars:
          stage: prod
      - terraform:
          stage: prod
          command: plan
      - slack/status

  tf_apply:
    executor: terraform
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - run:
          name: install required command
          command: apk --update add bash curl
      - setup_aws_credentials
      - create_tfvars:
          stage: << parameters.stage >>
      - terraform:
          stage: << parameters.stage >>
          command: apply -auto-approve
      - slack/status

workflows:
  build:
    jobs:
      - test
      - tf_plan

      - slack/approval-notification:
          requires: [test, tf_plan]
      - approval_deploy:
          type: approval
          requires: [test, tf_plan]

      #
      # dev
      #

      - tf_apply:
          name: tf_apply_dev
          stage: dev
          requires: [approval_deploy]

      #
      # prod
      #

      - tf_apply:
          name: tf_apply_prod
          stage: prod
          requires: [approval_deploy]
          filters:
            branches:
              only: [main]
