version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  node:
    docker:
      - image: node:12.18.0

  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24
        environment:
          TF_LOG: trace
          TF_LOG_PATH: terraform.log

commands:
  setup_aws_credentials:
    steps:
      - run:
          name: create aws credentials and config
          command: |
            mkdir -p ~/.aws
            echo '[default]'                                       > ~/.aws/credentials
            echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}"         >> ~/.aws/credentials
            echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
            echo '[default]'           > ~/.aws/config
            echo "region = us-east-1" >> ~/.aws/config

  yarn_install:
    steps:
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules

  terraform:
    parameters:
      stage:
        type: string
      command:
        type: string
    steps:
      - run:
          name: terraform init - << parameters.stage >>
          command: |
            cd ~/project/terraform/envs/<< parameters.stage >>
            terraform init
      - run:
          name: terraform << parameters.command >> - << parameters.stage >>
          command: |
            cd ~/project/terraform/envs/<< parameters.stage >>
            terraform << parameters.command >>
      - store_artifacts:
          path: terraform/envs/<< parameters.stage >>/terraform.log

jobs:
  test:
    executor: node
    steps:
      - checkout
      - yarn_install
      # - run:
      #     name: test
      #     command: yarn run test
      - run:
          name: build
          command: yarn run build

  tf_plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: install required command
          command: apk --update add bash curl
      - setup_aws_credentials
      - terraform:
          stage: dev
          command: plan
      - slack/status

workflows:
  build:
    jobs:
      - test
      - tf_plan
