version: '3'

services:
  app:
    command: sls offline --host 0.0.0.0 --httpPort 8080
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/app
      - aws:/root/.aws
      - node_modules:/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
      - jest_cache:/tmp/jest_cache

  infra:
    build:
      context: .
      dockerfile: ./containers/infra/Dockerfile
    volumes:
      - .:/app
      - aws:/root/.aws
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

volumes:
  aws:
  node_modules:
  yarn_cache:
  jest_cache:
