version: '3'

services:
  api:
    image: nojov-api
    build:
      context: .
      dockerfile: ./containers/app/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - yarn_cache:/usr/local/share/.cache/yarn/v6
      - jest_cache:/tmp/jest_cache

  infra:
    build:
      context: .
      dockerfile: ./containers/infra/Dockerfile
      args:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/app

volumes:
  node_modules:
  yarn_cache:
  jest_cache:
